language: java

jdk:
- oraclejdk8

script: mvn clean install jacoco:report coveralls:report

cache:
  directories:
    - node_modules

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: /home/travis/build/jonashackt/spring-boot-vuejs/backend/target
    skip_cleanup: true
    on: &1
      repo: jonashackt/spring-boot-vuejs
    bucket: spring-boot-vuejs-bucket
    region: eu-central-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-boot-vuejs-bucket
    key: backend-0.0.1-SNAPSHOT.jar
    bundle_type: zip
    application: spring-boot-vuejs
    deployment_group: spring-boot-apps
    region: eu-central-1
    on: *1
    wait-until-deployed: true

